# Streamlit Secrets Configuration Template
# Copy this file content to your Streamlit Cloud app's secrets section
# For local development, copy to .streamlit/secrets.toml with real values

# API Configuration
API_KEY = "io-v2-eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvd25lciI6IjFkY2YyZjI1LTI2MGItNDk3NC1iNmI3LWMzYmUyMzVhZmMwZCIsImV4cCI6NDkwNjQyOTA4MH0.ATps5dX6OhDOHdRW0M1HpH6RBYQ0DGMywXUAiNKN0yg0xvU3meN_TP0sU7WPXiPJh3erGm5ZcsIZY-ND2lP19A"
BASE_URL = "https://api.intelligence.io.solutions/api/v1"

# Environment Configuration
ENVIRONMENT = "production"

# Optional: Database configuration for cloud deployment
# DATABASE_URL = "postgresql://user:password@host:port/database"
# MEMORY_CONNECTION_STRING = "postgresql://user:password@host:port/database"

# Optional: Additional AI API Keys (if using multiple providers)
# OPENAI_API_KEY = "your-openai-key"
# ANTHROPIC_API_KEY = "your-anthropic-key"

# Optional: Feature Flags
ENABLE_DEMO_MODE = true
ENABLE_DEBUG_MODE = false

# Optional: Logging Configuration
LOG_LEVEL = "INFO"
